#!/usr/bin/env bash
set -Eeuo pipefail

thisDir="$(dirname "$(readlink -f "$BASH_SOURCE")")"
source "$thisDir/.constants.sh" \
	'<target-dir> <target-tar>' \
	'rootfs rootfs.tar'

targetDir="${1:-}"; shift || eusage 'missing target-dir'
[ -n "$targetDir" ]
targetTar="${1:-}"; shift || eusage 'missing target-tar'
[ -n "$targetTar" ]

epoch="$(< "$targetDir/docker-deboot-epoch")"
[ -n "$epoch" ]

"$thisDir/docker-deboot-fixup" "$targetDir"
tar --create \
	--file "$targetTar" \
	--auto-compress \
	--directory "$targetDir" \
	--exclude-from "$thisDir/.tar-exclude" \
	--numeric-owner \
	--transform 's,^./,,' \
	--sort name \
	.
touch --no-dereference --date="@$epoch" "$targetTar"
